### ISSUE TITLE
ICCV2021 Oral paper - Equivariant Imaging: Learning Beyond the Range Space

### ISSUE THREAD

**Issue by edongdongchen** [amusi/ICCV2021-Papers-with-Code#1]
ICCV2021 Oral paper: 

- Title: **Equivariant Imaging: Learning Beyond the Range Space**
- arXiv: [https://arxiv.org/abs/2103.14756](https://arxiv.org/abs/2103.14756)
- code: [https://github.com/edongdongchen/EI](https://github.com/edongdongchen/EI)
- topic: Self-supervised learning, Low-level vision, image reconstruction, inverse problem

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
