### ISSUE TITLE
ICCV 2021 paper: Manifold Matching via Deep Metric Learning for Generative Modeling

### ISSUE THREAD

**Issue by dzld00** [amusi/ICCV2021-Papers-with-Code#10]
Title: Manifold Matching via Deep Metric Learning for Generative Modeling
arXiv: https://arxiv.org/abs/2106.10777
Code: https://github.com/dzld00/pytorch-manifold-matching
Topic: Geometric deep learning | GAN

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
