### ISSUE TITLE
ICCV2021 paper: Channel-wise Topology Refinement Graph Convolution for Skeleton-Based Action Recognition

### ISSUE THREAD

**Issue by Uason-Chen** [amusi/ICCV2021-Papers-with-Code#11]
Title: Channel-wise Topology Refinement Graph Convolution for Skeleton-Based Action Recognition
arxiv: https://arxiv.org/abs/2107.12213
code: https://github.com/Uason-Chen/CTR-GCN
topic: action recognition

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
