### ISSUE TITLE
ICCV 21 Paper: Social NCE

### ISSUE THREAD

**Issue by YuejiangLIU** [amusi/ICCV2021-Papers-with-Code#12]
- Title: Social NCE: Contrastive Learning of Socially-aware Motion Representations
- Arxiv: https://arxiv.org/abs/2012.11717
- Code: https://github.com/vita-epfl/social-nce
- Topic: Trajectory Prediction | Contrastive Learning

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
