### ISSUE TITLE
ICCV2021: Self-Conditioned Probabilistic Learning of Video Rescaling

### ISSUE THREAD

**Issue by tianyuan168326** [amusi/ICCV2021-Papers-with-Code#13]
ICCV2021 paper:

Title: Self-Conditioned Probabilistic Learning of Video Rescaling
arXiv: https://arxiv.org/pdf/2107.11639.pdf
code: Under organizing
topic: Video Rescaling | Video Compression

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
