### ISSUE TITLE
ICCV2021- FREE: Feature Refinement for Generalized Zero-Shot Learning

### ISSUE THREAD

**Issue by shiming-chen** [amusi/ICCV2021-Papers-with-Code#14]
ICCV2021 paper: 

Title: FREE: Feature Refinement for Generalized Zero-Shot Learning
arXiv: https://arxiv.org/pdf/2107.13807.pdf
code: https://github.com/shiming-chen/FREE
topic: Zero-shot Learning | Knowledge transfer

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
