### ISSUE TITLE
ICCV 21 paper: Visual Alignment Constraint for Continuous Sign Language Recognition

### ISSUE THREAD

**Issue by ycmin95** [amusi/ICCV2021-Papers-with-Code#15]
Title: Visual Alignment Constraint for Continuous Sign Language Recognition
Arxiv: https://arxiv.org/abs/2104.02330
Code: https://github.com/ycmin95/VAC_CSLR
Topic: Sign Language Recognition | Sequence Learning | Action Recognition

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
