### ISSUE TITLE
ICCV 21 paper: Fast Convergence of DETR with Spatially Modulated Co-Attention

### ISSUE THREAD

**Issue by gaopengcuhk** [amusi/ICCV2021-Papers-with-Code#17]
Fast Convergence of DETR with Spatially Modulated Co-Attention

https://arxiv.org/abs/2101.07448

https://github.com/abc403/SMCA-replication

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing

**Comment by gaopengcuhk** [comment]
Can you update the GitHub link to the following link?

https://github.com/gaopengcuhk/SMCA-DETR

Best Wishes
