### ISSUE TITLE
Please add our paper

### ISSUE THREAD

**Issue by hwjiang1510** [amusi/ICCV2021-Papers-with-Code#2]
Hand-Object Contact Consistency Reasoning for Human Grasps Generation (accepted as Oral)

Project page: https://hwjiang1510.github.io/GraspTTA/
Arxiv: https://arxiv.org/pdf/2104.03304.pdf
Topic: 3D vision, affordance reasoning, pose estimation

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
