### ISSUE TITLE
ICCV Paper: IDM: An Intermediate Domain Module for Domain Adaptive Person Re-ID

### ISSUE THREAD

**Issue by SikaStar** [amusi/ICCV2021-Papers-with-Code#20]
Hi, thanks for your collections! Please add our paper:

Paper (ICCV 2021 Oral): https://arxiv.org/abs/2108.02413
Code: https://github.com/SikaStar/IDM

Thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
