### ISSUE TITLE
ICCV 2021 paper: Conditional DETR for Fast Training Convergence

### ISSUE THREAD

**Issue by charlesCXK** [amusi/ICCV2021-Papers-with-Code#22]
Hi,
Official code of our paper "Conditional DETR for Fast Training Convergence" (https://arxiv.org/abs/2108.06152) has been released, please see https://github.com/Atten4Vis/ConditionalDETR

Hope you can add this link to your README file,
thanks.

Topic:
Transformer, Object Detection

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
