### ISSUE TITLE
ICCV 2021 paper: Relational Embedding for Few-Shot Classification

### ISSUE THREAD

**Issue by dahyun-kang** [amusi/ICCV2021-Papers-with-Code#24]
Hello,

Please consider including our paper "Relational Embedding for Few-Shot Classification" (https://arxiv.org/abs/2108.09666) as well as its code (https://github.com/dahyun-kang/renet) in the "Few-shot learning" category.

Have a great day! :smiley:

Best, 
Dahyun

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
