### ISSUE TITLE
ICCV 2021 paper: RINDNet: Edge Detection for Discontinuity in Reflectance, Illumination, Normal and Depth

### ISSUE THREAD

**Issue by MengyangPu** [amusi/ICCV2021-Papers-with-Code#25]
Title: RINDNet: Edge Detection for Discontinuity in Reflectance, Illumination, Normal and Depth
Arxiv: https://arxiv.org/abs/2108.00616
Dataset and Code: https://github.com/MengyangPu/RINDNet
Topic: Edge Detection

**Comment by amusi** [comment]
RINDNet: Edge Detection for Discontinuity in Reflectance, Illumination, Normal and Depth
