### ISSUE TITLE
ICCV 2021 paper: Geometry-based Distance Decomposition for Monocular 3D Object Detection

### ISSUE THREAD

**Issue by Rock-100** [amusi/ICCV2021-Papers-with-Code#26]
Title: Geometry-based Distance Decomposition for Monocular 3D Object Detection
Arxiv: https://arxiv.org/abs/2104.03775
Code: https://github.com/Rock-100/MonoDet
Topic: Monocular 3D Object Detection

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
