### ISSUE TITLE
ICCV 2021 paper: Learning Conditional Knowledge Distillation for Degraded-Reference Image Quality Assessment

### ISSUE THREAD

**Issue by Heliang-Zheng** [amusi/ICCV2021-Papers-with-Code#27]
Title: Learning Conditional Knowledge Distillation for Degraded-Reference Image Quality Assessment
Arxiv: https://arxiv.org/abs/2108.07948
Code: https://github.com/researchmm/CKDN
Topic: Image Quality Assessment, Image Restoration

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
