### ISSUE TITLE
ICCV 2021 paper - Generalize then Adapt: Source-Free Domain Adaptive Semantic Segmentation

### ISSUE THREAD

**Issue by akshaykvnit** [amusi/ICCV2021-Papers-with-Code#29]
Title - Generalize then Adapt: Source-Free Domain Adaptive Semantic Segmentation
Arxiv - https://arxiv.org/abs/2108.11249
Project page - https://sites.google.com/view/sfdaseg (code link will be updated here)
Topic - Unsupervised Domain Adaptation (for Semantic Segmentation)

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
