### ISSUE TITLE
Another work on Self-Supervised Learning

### ISSUE THREAD

**Issue by hansen7** [amusi/ICCV2021-Papers-with-Code#3]
Hi @amusi, thanks for creating this list!  

We have a paper on self-supervised pre-training on point cloud accepted by ICCV this year. 
It would be so nice of you to include our work :)

Project Page: https://hansen7.github.io/OcCo/
Code: https://github.com/hansen7/OcCo
Paper: https://arxiv.org/abs/2010.01089

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
