### ISSUE TITLE
ICCV-2021 Paper: Few Shot Visual Relationship Co-Localization

### ISSUE THREAD

**Issue by its-mayank** [amusi/ICCV2021-Papers-with-Code#31]
Title - Few Shot Visual Relationship Co-Localization
Arxiv - https://arxiv.org/abs/2108.11618
Project page (with code) -https://vl2g.github.io/projects/vrc/
Topic - Few-Shot Learning

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
