### ISSUE TITLE
ICCV-2021 Paper: Generating Attribution Maps with Disentangled Masked Backpropagation

### ISSUE THREAD

**Issue by adriaruizo** [amusi/ICCV2021-Papers-with-Code#34]
Title - Generating Attribution Maps with Disentangled Masked Backpropagation
Arxiv - https://arxiv.org/pdf/2101.06773.pdf
Code - https://gitlab.com/adriaruizo/dmbp_iccv21
Topic - Feature Attribution Visualization

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
