### ISSUE TITLE
ICCV 2021 Paper: Towards Flexible Blind JPEG Artifacts Removal 

### ISSUE THREAD

**Issue by jiaxi-jiang** [amusi/ICCV2021-Papers-with-Code#37]
Paper: https://arxiv.org/pdf/2109.14573.pdf
Code: https://github.com/jiaxi-jiang/FBCNN

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing

**Comment by jiaxi-jiang** [comment]
Thanks. BTW, it is in the area of image restoration.
