### ISSUE TITLE
ICCV-2021 Paper: Image Classification and Depth Estimation in extreme low-light

### ISSUE THREAD

**Issue by bhavyagoyal** [amusi/ICCV2021-Papers-with-Code#39]
ICCV 2021: Photon-Starved Scene Inference using Single Photon Cameras

Paper: https://openaccess.thecvf.com/content/ICCV2021/papers/Goyal_Photon-Starved_Scene_Inference_Using_Single_Photon_Cameras_ICCV_2021_paper.pdf

Code: https://github.com/bhavyagoyal/spclowlight

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
