### ISSUE TITLE
ICCV2021 Oral paper: GNeRF: GAN-based Neural Radiance Field without Posed Camera

### ISSUE THREAD

**Issue by MQ66** [amusi/ICCV2021-Papers-with-Code#4]
ICCV2021 Oral paper:

Title: GNeRF: GAN-based Neural Radiance Field without Posed Camera
arXiv: https://arxiv.org/abs/2103.15606
code: https://github.com/MQ66/gnerf
topic: NeRF

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
