### ISSUE TITLE
ICCV-2021 Paper: Instance Segmentation in 3D Scenes Using Semantic Superpoint Tree Networks

### ISSUE THREAD

**Issue by lzhnb** [amusi/ICCV2021-Papers-with-Code#42]
Category: 3D Instance Segmentation(3D实例分割)

Paper: https://openaccess.thecvf.com/content/ICCV2021/html/Liang_Instance_Segmentation_in_3D_Scenes_Using_Semantic_Superpoint_Tree_Networks_ICCV_2021_paper.html

Code: https://github.com/Gorilla-Lab-SCUT/SSTNet

Thank you~

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
