### ISSUE TITLE
ICCV 2021 paper CPF: Learning a Contact Potential Field to Model the Hand-Object Interaction

### ISSUE THREAD

**Issue by lixiny** [amusi/ICCV2021-Papers-with-Code#5]
ICCV2021 paper:

Title: CPF: Learning a Contact Potential Field to Model the Hand-Object Interaction
arXiv: https://arxiv.org/pdf/2012.00924.pdf
code: https://lixiny.github.io/CPF
topic: Hand-Object

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
