### ISSUE TITLE
ICCV 21 Paper: Why Approximate Matrix Square Root Outperforms Accurate SVD in Global Covariance Pooling?

### ISSUE THREAD

**Issue by KingJamesSong** [amusi/ICCV2021-Papers-with-Code#6]
Title: Why Approximate Matrix Square Root Outperforms Accurate SVD in Global Covariance Pooling?
Arxiv: https://arxiv.org/abs/2105.02498
Link: https://github.com/KingJamesSong/DifferentiableSVD
Topic: Backbone | Others

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
