### ISSUE TITLE
ICCV 21 paper:  VLGrammar: Grounded Grammar Induction of Vision and Language

### ISSUE THREAD

**Issue by evelinehong** [amusi/ICCV2021-Papers-with-Code#7]
Can you kindly add my paper?

Yining Hong; Qing Li; Song-Chun Zhu; Siyuan Huang, "VLGrammar: Grounded Grammar Induction of Vision and Language", ICCV2021

pdf: https://arxiv.org/abs/2103.12975
code: https://github.com/evelinehong/VLGrammar

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
