### ISSUE TITLE
ICCV 2021 oral paper: Generalized Shuffled Linear Regression

### ISSUE THREAD

**Issue by SILI1994** [amusi/ICCV2021-Papers-with-Code#8]
Hi, Thank you for creating this! 
Would you like to kindly add our ICCV 2021 oral paper:  Generalized Shuffled Linear Regression

Code and paper:  https://github.com/SILI1994/Generalized-Shuffled-Linear-Regression
Topic: Others, point cloud registration.

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing

**Comment by SILI1994** [comment]
Hi! Thank you for adding it and sorry for bothering again.  But I would really appreciate it if a note of "oral"  for our paper can be added to the current list.
